/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/burger_restaurant.glb 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-burger-restaurant-90d7b38c42ec4ebdbd6646fe4ece9547
Title: Low poly burger restaurant
*/

import { Html, useGLTF } from "@react-three/drei";
import React from "react";


export function Camping({ ...props }) {
  const { nodes, materials } = useGLTF("/burger_restaurant.glb");
  return (
    <group {...props} dispose={null} scale={1.6}>
      <directionalLight position={[0, 0, 7]} intensity={2} />
      <ambientLight intensity={0.2} />
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.BurgerBuilding_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          
          <mesh
            geometry={nodes.BurgerBurger_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.BurgerText_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.BurgerPlants_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.BurgerTables_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.Collider_Collider_0.geometry}
            material={materials.Collider}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/burger_restaurant.glb");
