/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Camping Asset Collection.glb -o src/components/Camping.jsx -k -K -r public
*/

import { Html, useGLTF } from "@react-three/drei";
import { useAtom } from "jotai";
import React from "react";
import { degToRad } from "three/src/math/MathUtils";
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'
import { useRef } from "react";
import { useHelper } from "@react-three/drei";
import * as THREE from "three";


export function Camping({ html, ...props }) {
 const { scene } = useGLTF('/gaz.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)  
    const lightRef = useRef();
  // useHelper(lightRef, THREE.DirectionalLightHelper, 1, "hotpink");

  return (
    <group {...props} dispose={null}>
      {/* <ambientLight intensity={4} /> */}
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <directionalLight
        ref={lightRef}
        position={[0, 10, 4]} // Прямо сверху
        intensity={4}
        castShadow
        shadow-mapSize={[1024, 1024]}
        shadow-camera-far={20}
        shadow-camera-near={1}
        shadow-camera-top={10}
        shadow-camera-bottom={-10}
        shadow-camera-left={-10}
        shadow-camera-right={10}
      />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        skeleton={nodes.Object_7.skeleton}
      >
        <meshPhysicalMaterial
          color="SkyBlue" // Яркий пурпурно-розовый
          metalness={0.8}
          roughness={0.4}
          anisotropicBlur={0.5} // Размытие анизотропных отражений
          anisotropicRotation={0.9} // Вращение анизотропного эффекта
          clearcoat={0.5}
          envMapIntensity={1.0}
        />{" "}
      </skinnedMesh>
      <skinnedMesh
        geometry={nodes.Object_8.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_8.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_9.geometry}
        material={materials.Interior_light}
        skeleton={nodes.Object_9.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_10.geometry}
        material={materials.Interior_dark}
        skeleton={nodes.Object_10.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_11.geometry}
        material={materials.Derma}
        skeleton={nodes.Object_11.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_12.geometry}
        material={materials.Black_plastic}
        skeleton={nodes.Object_12.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_13.geometry}
        material={materials.Glass}
        skeleton={nodes.Object_13.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_14.geometry}
        material={materials.Reverse_lights}
        skeleton={nodes.Object_14.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_15.geometry}
        material={materials.Tail_lights}
        skeleton={nodes.Object_15.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_16.geometry}
        material={materials.Orange_plastic}
        skeleton={nodes.Object_16.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_17.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_17.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_18.geometry}
        material={materials.Underbody}
        skeleton={nodes.Object_18.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_20.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_20.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_22.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_22.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_23.geometry}
        material={materials.Black_plastic}
        skeleton={nodes.Object_23.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_24.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_24.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_25.geometry}
        material={materials.Black_Paint}
        skeleton={nodes.Object_25.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_26.geometry}
        material={materials.Steel}
        skeleton={nodes.Object_26.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_27.geometry}
        material={materials.Reflector}
        skeleton={nodes.Object_27.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_29.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_29.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_30.geometry}
        material={materials.material}
        skeleton={nodes.Object_30.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_32.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_32.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_33.geometry}
        material={materials.Reflector}
        skeleton={nodes.Object_33.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/gaz.glb");
