"use client";

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useHelper } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

import { useRef } from "react";
import * as THREE from "three";
import { TransformControls } from "@react-three/drei";
import { useState } from "react";

export default function Kitchen2(...props) {
  const { nodes, materials } = useGLTF("/kitchen2.glb");

  return (
    <group {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <group position={[-4306.855, 0, 1410.551]}>
            <mesh
              geometry={nodes.FrontSide_0.geometry}
              material={
                materials.RGBAMaterial_000000000_000000000_000000000_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_1.geometry}
              material={
                materials.RGBAMaterial_002745098_006274510_017647059_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_2.geometry}
              material={
                materials.RGBAMaterial_016862746_014509805_055686277_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_3.geometry}
              material={
                materials.RGBAMaterial_056470591_015686275_020000000_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_4.geometry}
              material={
                materials.RGBAMaterial_071764708_063921571_056078434_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_5.geometry}
              material={
                materials.RGBAMaterial_080000001_080000001_080000001_100000000
              }
            />
            <mesh
              geometry={nodes.FrontSide_6.geometry}
              material={materials.TextureMaterial}
            />
            <mesh
              geometry={nodes.FrontSide_7.geometry}
              material={materials.TextureMaterial_1}
            />
            <mesh
              geometry={nodes.FrontSide_8.geometry}
              material={materials.TextureMaterial_10}
            />
            <mesh
              geometry={nodes.FrontSide_9.geometry}
              material={materials.TextureMaterial_11}
            />
            <mesh
              geometry={nodes.FrontSide_10.geometry}
              material={materials.TextureMaterial_12}
            />
            <mesh
              geometry={nodes.FrontSide_11.geometry}
              material={materials.TextureMaterial_13}
            />
            <mesh
              geometry={nodes.FrontSide_12.geometry}
              material={materials.TextureMaterial_14}
            />
            <mesh
              geometry={nodes.FrontSide_13.geometry}
              material={materials.TextureMaterial_15}
            />
            <mesh
              geometry={nodes.FrontSide_14.geometry}
              material={materials.TextureMaterial_16}
            />
            <mesh
              geometry={nodes.FrontSide_15.geometry}
              material={materials.TextureMaterial_17}
            />
            <mesh
              geometry={nodes.FrontSide_16.geometry}
              material={materials.TextureMaterial_18}
            />
            <mesh
              geometry={nodes.FrontSide_17.geometry}
              material={materials.TextureMaterial_19}
            />
            <mesh
              geometry={nodes.FrontSide_18.geometry}
              material={materials.TextureMaterial_2}
            />
            <mesh
              geometry={nodes.FrontSide_19.geometry}
              material={materials.TextureMaterial_20}
            />
            <mesh
              geometry={nodes.FrontSide_20.geometry}
              material={materials.TextureMaterial_21}
            />
            <mesh
              geometry={nodes.FrontSide_21.geometry}
              material={materials.TextureMaterial_22}
            />
            <mesh
              geometry={nodes.FrontSide_22.geometry}
              material={materials.TextureMaterial_23}
            />
            <mesh
              geometry={nodes.FrontSide_23.geometry}
              material={materials.TextureMaterial_24}
            />
            <mesh
              geometry={nodes.FrontSide_24.geometry}
              material={materials.TextureMaterial_25}
            />
            <mesh
              geometry={nodes.FrontSide_25.geometry}
              material={materials.TextureMaterial_26}
            />
            <mesh
              geometry={nodes.FrontSide_26.geometry}
              material={materials.TextureMaterial_27}
            />
            <mesh
              geometry={nodes.FrontSide_27.geometry}
              material={materials.TextureMaterial_28}
            />
            <mesh
              geometry={nodes.FrontSide_28.geometry}
              material={materials.TextureMaterial_29}
            />
            <mesh
              geometry={nodes.FrontSide_29.geometry}
              material={materials.TextureMaterial_3}
            />
            <mesh
              geometry={nodes.FrontSide_30.geometry}
              material={materials.TextureMaterial_30}
            />
            <mesh
              geometry={nodes.FrontSide_31.geometry}
              material={materials.TextureMaterial_31}
            />
            <mesh
              geometry={nodes.FrontSide_32.geometry}
              material={materials.TextureMaterial_32}
            />
            <mesh
              geometry={nodes.FrontSide_33.geometry}
              material={materials.TextureMaterial_33}
            />
            <mesh
              geometry={nodes.FrontSide_34.geometry}
              material={materials.TextureMaterial_34}
            />
            <mesh
              geometry={nodes.FrontSide_35.geometry}
              material={materials.TextureMaterial_35}
            />
            <mesh
              geometry={nodes.FrontSide_36.geometry}
              material={materials.TextureMaterial_36}
            />
            <mesh
              geometry={nodes.FrontSide_37.geometry}
              material={materials.TextureMaterial_37}
            />
            <mesh
              geometry={nodes.FrontSide_38.geometry}
              material={materials.TextureMaterial_38}
            />
            <mesh
              geometry={nodes.FrontSide_39.geometry}
              material={materials.TextureMaterial_39}
            />
            <mesh
              geometry={nodes.FrontSide_40.geometry}
              material={materials.TextureMaterial_4}
            />
            <mesh
              geometry={nodes.FrontSide_41.geometry}
              material={materials.TextureMaterial_40}
            />
            <mesh
              geometry={nodes.FrontSide_42.geometry}
              material={materials.TextureMaterial_41}
            />
            <mesh
              geometry={nodes.FrontSide_43.geometry}
              material={materials.TextureMaterial_42}
            />
            <mesh
              geometry={nodes.FrontSide_44.geometry}
              material={materials.TextureMaterial_43}
            />
            <mesh
              geometry={nodes.FrontSide_45.geometry}
              material={materials.TextureMaterial_44}
            />
            <mesh
              geometry={nodes.FrontSide_46.geometry}
              material={materials.TextureMaterial_45}
            />
            <mesh
              geometry={nodes.FrontSide_47.geometry}
              material={materials.TextureMaterial_46}
            />
            <mesh
              geometry={nodes.FrontSide_48.geometry}
              material={materials.TextureMaterial_47}
            />
            <mesh
              geometry={nodes.FrontSide_49.geometry}
              material={materials.TextureMaterial_48}
            />
            <mesh
              geometry={nodes.FrontSide_50.geometry}
              material={materials.TextureMaterial_49}
            />
            <mesh
              geometry={nodes.FrontSide_51.geometry}
              material={materials.TextureMaterial_5}
            />
            <mesh
              geometry={nodes.FrontSide_52.geometry}
              material={materials.TextureMaterial_50}
            />
            <mesh
              geometry={nodes.FrontSide_53.geometry}
              material={materials.TextureMaterial_51}
            />
            <mesh
              geometry={nodes.FrontSide_54.geometry}
              material={materials.TextureMaterial_52}
            />
            <mesh
              geometry={nodes.FrontSide_55.geometry}
              material={materials.TextureMaterial_53}
            />
            <mesh
              geometry={nodes.FrontSide_56.geometry}
              material={materials.TextureMaterial_54}
            />
            <mesh
              geometry={nodes.FrontSide_57.geometry}
              material={materials.TextureMaterial_55}
            />
            <mesh
              geometry={nodes.FrontSide_58.geometry}
              material={materials.TextureMaterial_56}
            />
            <mesh
              geometry={nodes.FrontSide_59.geometry}
              material={materials.TextureMaterial_57}
            />
            <mesh
              geometry={nodes.FrontSide_60.geometry}
              material={materials.TextureMaterial_58}
            />
            <mesh
              geometry={nodes.FrontSide_61.geometry}
              material={materials.TextureMaterial_59}
            />
            <mesh
              geometry={nodes.FrontSide_62.geometry}
              material={materials.TextureMaterial_6}
            />
            <mesh
              geometry={nodes.FrontSide_63.geometry}
              material={materials.TextureMaterial_60}
            />
            <mesh
              geometry={nodes.FrontSide_64.geometry}
              material={materials.TextureMaterial_61}
            />
            <mesh
              geometry={nodes.FrontSide_65.geometry}
              material={materials.TextureMaterial_62}
            />
            <mesh
              geometry={nodes.FrontSide_66.geometry}
              material={materials.TextureMaterial_63}
            />
            <mesh
              geometry={nodes.FrontSide_67.geometry}
              material={materials.TextureMaterial_64}
            />
            <mesh
              geometry={nodes.FrontSide_68.geometry}
              material={materials.TextureMaterial_65}
            />
            <mesh
              geometry={nodes.FrontSide_69.geometry}
              material={materials.TextureMaterial_66}
            />
            <mesh
              geometry={nodes.FrontSide_70.geometry}
              material={materials.TextureMaterial_7}
            />
            <mesh
              geometry={nodes.FrontSide_71.geometry}
              material={materials.TextureMaterial_8}
            />
            <mesh
              geometry={nodes.FrontSide_72.geometry}
              material={materials.TextureMaterial_9}
            />
            <mesh
              geometry={nodes.BackSide_0.geometry}
              material={materials.TextureMaterial_19}
            />
            <mesh
              geometry={nodes.BackSide_1.geometry}
              material={materials.TextureMaterial_2}
            />
            <mesh
              geometry={nodes.BackSide_2.geometry}
              material={materials.TextureMaterial_20}
            />
            <mesh
              geometry={nodes.BackSide_3.geometry}
              material={materials.TextureMaterial_45}
            />
            <mesh
              geometry={nodes.BackSide_4.geometry}
              material={materials.TextureMaterial_67}
            />
            <mesh
              geometry={nodes.BackSide_4_1.geometry}
              material={materials.TextureMaterial_67}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/kitchen2.glb");
