
import "./globals.css";
import {Nunito} from 'next/font/google'


const nunito = Nunito({
  subsets: ['cyrillic'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={nunito.className}>
        
        {children}
  
      </body>
    </html>
  );
}
